Repository MoguProject/mogu-front, pull requests merged in 2022-12, with the labels that each got.

#27 [#25] ✨ feat: 프로젝트/스터디 모집하기 페이지 레이아웃 구현
  components/common/button/register/index.tsx
  components/project-study/DesktopHeader/index.tsx
  components/project-study/DesktopHeader/styled.ts
  components/registration/Editor/index.tsx
  components/registration/index.tsx
  components/registration/styled.ts
  next.config.js
  package-lock.json
  package.json
  pages/registration/index.tsx
  pages/registration/styled.ts
  yarn.lock
Labels: Component, Desktop

#35 Feature/community
  components/Layout/Header/index.tsx
  components/common/post/CommunityPost/index.tsx
  components/common/post/CommunityPost/styled.ts
  components/community/CommunityHeader/index.tsx
  components/community/CommunityHeader/top/index.tsx
  components/community/CommunityWrapper/index.tsx
  components/main/MainBottom/MainBottomLeft/index.tsx
  components/main/MainBottom/MainBottomLeft/styled.ts
  components/registration/cummunity/index.tsx
  package-lock.json
  package.json
  pages/community/category/[id].tsx
  pages/community/detail/[id].tsx
  pages/community/index.tsx
  pages/registration/community/index.tsx
  utils/apis/posts.ts
  yarn.lock
Labels: Component, Mobile, Desktop

#46 :sparkles: [#24] feat: 커뮤니티 페이지 레이아웃 구현
  components/community/CommunityWrapper/index.tsx
  components/registration/PostEditor/index.tsx
  components/registration/cummunity/index.tsx
  components/registration/index.tsx
  pages/community/index.tsx
  utils/apis/posts.ts
  yarn.lock
Labels: Component, Desktop

#47 ✨ [#17] feat : 프로젝트 스터디 게시물 보여주기, 페이지네이션, 정렬 기능 구현
  components/auth/Signup/index.tsx
  components/common/FilteredBox/index.tsx
  components/common/Pagination/index.tsx
  components/common/Pagination/styled.ts
  components/common/card/project/ProjectDesktopCard/index.tsx
  components/common/card/project/ProjectDesktopCard/styled.ts
  components/detail/DetailCommentForm.tsx
  components/detail/DetailWrapper.tsx
  components/main/MainNewContent/index.tsx
  components/mypage/MyPageEditProfile/MyPagePasswordWrapper/index.tsx
  components/project-study/DesktopHeader/index.tsx
  components/project-study/DesktopHeader/styled.ts
  components/project-study/index.tsx
  config/config.ts
  hooks/useIsMobile.ts
  next.config.js
  pages/projects/detail.tsx
  pages/projects/index.tsx
  pages/projects/styled.ts
  tsconfig.json
  types/index.ts
  utils/apis/posts.ts
  utils/apis/user.ts
Labels: Component, Desktop

#48 [#24] ✨ feat : 커뮤니티 페이지 페이지네이션, 필터링, 카테고리 기능 구현
  components/common/Pagination/index.tsx
  components/common/post/CommunityPost/index.tsx
  components/community/CommunityHeader/index.tsx
  components/community/CommunityHeader/styled.ts
  components/community/CommunityHeader/top/index.tsx
  components/community/CommunityWrapper/index.tsx
  package-lock.json
  package.json
  pages/community/index.tsx
  pages/projects/index.tsx
  types/index.ts
  utils/apis/posts.ts
  yarn.lock
Labels: Component, Desktop

#50 :sparkles: [#49] feat: 커뮤니티 상세 페이지 기능 구현
  components/Layout/Header/index.tsx
  components/community/CommunityReview/comment.tsx
  components/community/CommunityReview/index.tsx
  components/community/CommunityReview/reply.tsx
  components/community/CommunityReview/styled.ts
  components/detail/DetailCommentForm.tsx
  components/detail/DetailWrapper.tsx
  components/registration/cummunity/index.tsx
  pages/community/category/[id].tsx
  pages/community/detail/[id].tsx
  pages/community/detail/styled.ts
  styles/theme.ts
  types/index.ts
  utils/apis/posts.ts
Labels: Component

#51 Feature/community
  components/common/post/CommunityPost/index.tsx
  components/community/CommunityReview/comment.tsx
  components/detail/DetailCommentForm.tsx
  components/detail/DetailWrapper.tsx
  components/registration/cummunity/edit/index.tsx
  components/registration/cummunity/index.tsx
  pages/community/detail/index.tsx
  pages/index.tsx
  pages/registration/community/edit/index.tsx
Labels: Component

#58 [#57] ✨ feat : 프로젝트 스터디 글쓰기 페이지 구현
  axiosInstance/index.ts
  components/auth/Login/index.tsx
  components/common/Modal/index.tsx
  components/common/input/SelectInput/index.tsx
  components/detail/DetailCommentForm.tsx
  components/detail/DetailWrapper.tsx
  components/registration/Community/edit/index.tsx
  components/registration/Community/index.tsx
  components/registration/Community/styled.ts
  components/registration/Editor/index.tsx
  components/registration/ProjectStudy/ProjectStudyForm/index.tsx
  components/registration/ProjectStudy/ProjectStudyForm/options.ts
  components/registration/ProjectStudy/index.tsx
  components/registration/index.tsx
  config/config.ts
  dummy/ProjectsData.ts
  dummy/StudyData.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/community/detail/index.tsx
  pages/index.tsx
  pages/mypage/index.tsx
  pages/registration/community/edit/index.tsx
  pages/registration/community/index.tsx
  pages/registration/projectstudy/index.tsx
  public/images/icon/camera.svg
  recoil/atom.ts
  utils/apis/user.ts
  yarn.lock
Labels: Component
