Repository MoguProject/mogu-front, pull requests merged in 2022-11, with the labels that each got.

#3 GlobalFont 및 ColorTheme 설정
  pages/_app.tsx
  styles/globalStyle.ts
  styles/styled.d.ts
  styles/theme.ts
Labels: global

#6 Desktop Header Component 구현
  components/Layout/Header/index.tsx
  components/Layout/Header/styled.ts
  pages/index.tsx
Labels: Component

#7 [#5] ✨ feat: Desktop Footer Component 구현
  components/Layout/Footer/index.tsx
  components/Layout/Footer/styled.ts
  pages/index.tsx
Labels: Component

#13 [#9] ✨ feat: [데스크탑]스터디 카드 컴포넌트 구현
  components/common/card/study/StudyDesktopCard.tsx
  components/common/card/study/styled.ts
  pages/index.tsx
Labels: Component, Desktop

#12 [#11] ✨ feat: title, meta 태그 활용한 seo 최적화
  pages/_app.tsx
Labels: SEO

#16 [#15]✨ feat: 메인페이지 캐러셀 구현 및 레이아웃 작업
  components/Layout/Footer/styled.ts
  components/Layout/index.tsx
  components/common/card/project/ProjectDesktopCard/index.tsx
  components/common/card/project/ProjectMobileCard/index.tsx
  components/common/card/study/StudyDesktopCard.tsx
  components/common/card/study/styled.ts
  components/main/CardCarousel/index.tsx
  components/main/CardCarousel/styled.ts
  components/main/MainNewContent/index.tsx
  pages/index.tsx
  public/images/icon/chevron_next.svg
  public/images/icon/chevron_prev.svg
  styles/globalStyle.ts
Labels: Component

#19 ✨ [#17] feat : 프로젝트/스터디 페이지 레이아웃 작업
  components/Layout/Header/index.tsx
  components/common/FilteredBox/index.tsx
  components/common/FilteredBox/styled.ts
  components/common/button/register/index.tsx
  components/common/card/study/StudyCard.tsx
  components/main/MainNewContent/index.tsx
  components/project-study/header/index.tsx
  components/project-study/header/styled.ts
  dummy/ProjectsData.ts
  package-lock.json
  package.json
  pages/index.tsx
  pages/projects/[projectsId].tsx
  pages/projects/index.tsx
  pages/projects/styled.ts
  pages/study/[studyId].tsx
  pages/study/index.tsx
  yarn.lock
Labels: Component, Desktop

#20 ✨ [#17] feat : 메인페이지 포스트 컴포넌트 및 하단부 레이아웃 작업
  components/common/buttons/MoreButton/index.tsx
  components/common/buttons/MoreButton/styled.ts
  components/common/post/CommunityPost/index.tsx
  components/common/post/CommunityPost/styled.ts
  components/common/post/ProjectPost/index.tsx
  components/common/post/ProjectPost/styled.ts
  components/common/post/StudyPost/index.tsx
  components/common/post/StudyPost/styled.ts
  components/main/MainBottom/MainBottomLeft/index.tsx
  components/main/MainBottom/MainBottomLeft/styled.ts
  components/main/MainBottom/MainBottomRight/index.tsx
  components/main/MainBottom/MainBottomRight/styled.ts
  components/main/MainBottom/index.tsx
  components/main/MainBottom/styled.ts
  pages/index.tsx
  public/images/dummy_avatar.svg
  public/images/icon/eye.svg
Labels: Component, Desktop

#23 [#18]✨ feat : 로그인, 회원가입 페이지 구현 및 유효성검사 적용
  components/Layout/Footer/styled.ts
  components/Layout/index.tsx
  components/auth/Login/index.tsx
  components/auth/Login/styled.ts
  components/auth/Signup/index.tsx
  components/auth/Signup/styled.ts
  components/common/button/AuthButton/index.tsx
  pages/auth/login.tsx
  pages/auth/signup.tsx
  styles/globalStyle.ts
  types/index.ts
Labels: Component

#22 [#17] ✨ feat : [모바일] 프로젝트/스터디 페이지 레이아웃 작업 및 [데스크탑] 스타일 수정
  components/Layout/Footer/Desktop/index.tsx
  components/Layout/Footer/Desktop/styled.ts
  components/Layout/Footer/Mobile/index.tsx
  components/Layout/Footer/Mobile/styed.ts
  components/Layout/Footer/index.tsx
  components/common/FilteredBox/index.tsx
  components/common/FilteredBox/styled.ts
  components/common/card/project/ProjectDesktopCard/index.tsx
  components/common/card/project/ProjectMobileCard/index.tsx
  components/common/card/study/StudyCard.tsx
  components/main/MainNewContent/index.tsx
  components/project-study/DesktopHeader/index.tsx
  components/project-study/DesktopHeader/styled.ts
  components/project-study/index.tsx
  dummy/StudyData.ts
  pages/projects/index.tsx
  pages/projects/styled.ts
  pages/study/index.tsx
  public/images/icon/chevron-right.svg
Labels: Component, Mobile, Desktop, dummy

#26 [#24] ✨ feat : 커뮤니티 페이지 데스크탑 레이아웃 구현
  components/Layout/Header/index.tsx
  components/common/Pagination/index.tsx
  components/common/Pagination/styled.ts
  components/common/input/SearchInput/index.tsx
  components/common/input/SearchInput/styled.ts
  components/common/input/SelectInput/index.tsx
  components/community/CommunityHeader/index.tsx
  components/community/CommunityHeader/styled.ts
  components/community/CommunityWrapper/index.tsx
  next.config.js
  package-lock.json
  package.json
  pages/community/index.tsx
  public/images/icon/caret.svg
  public/images/icon/chevron_next.svg
  public/images/icon/chevron_prev.svg
  public/images/icon/search.svg
  tsconfig.json
  yarn.lock
Labels: Component, Desktop
